/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtable;
import java.util.Date; 
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ButtonModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import static jtable.AdminFrame.ID;

/**
 *
 * @author RAMYAMUKESH
 */
public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();
        address="C:\\Users\\RAMYAMUKESH\\Documents\\project\\filss\\";
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        jRadioButton1.setSelected(true);      
        jRadioButton1.setActionCommand("Cash");
        jRadioButton2.setActionCommand("card");
        jRadioButton3.setActionCommand("Upi");
        ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
      public void valueChanged(ListSelectionEvent e) {
        String selectedData = null;
        int selectedRow = jTable1.getSelectedRow();
        int selectedColumn = jTable1.getSelectedColumn();
      }

    });
    jTable1.getModel().addTableModelListener(new TableModelListener() {

      public void tableChanged(TableModelEvent e) {
        
       
        if(e.getColumn()==4)return;
        int p=0,r=e.getFirstRow(),c=e.getColumn(),i=0,n=0;
        float f=0;
         if(e.getColumn()==-1)    
        {n=jTable1.getRowCount();
         for(i=0;i<n;i++)
            {
                f+=(float)jTable1.getValueAt(i, 4);
            }
         jLabel4.setText(String.valueOf(f));
         return;
        }
      
        try{ 
            p= Integer.valueOf((String) jTable1.getValueAt(r, c));
        }
        catch(NumberFormatException k)
            {
                jTable1.setValueAt(1, r, c);
                 JOptionPane.showMessageDialog(jFrame1, "Enter valid quantity","Failed ", JOptionPane.ERROR_MESSAGE);
                 return;
            }
        jTable1.setValueAt(Float.valueOf((String)jTable1.getValueAt(e.getFirstRow(), 2))*p, r, 4);
         n=jTable1.getRowCount();
         for(i=0;i<n;i++)
            {
                f+=(float)jTable1.getValueAt(i, 4);
            }
         jLabel4.setText(String.valueOf(f));
      }

           
    });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        jFrame1.setTitle("MultipleProducts");
        jFrame1.setSize(new java.awt.Dimension(647, 260));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BarcodeId", "uniqueId", "Name", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, -1, 215));

        jButton2.setText("enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jFrame2.setTitle("NewCustomer");
        jFrame2.setMinimumSize(new java.awt.Dimension(509, 299));
        jFrame2.setSize(new java.awt.Dimension(509, 299));
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 126, 138, 20));

        jLabel6.setText("Name");
        jFrame2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 129, -1, -1));

        jLabel7.setText("New User");
        jFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 94, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UniqueID", "Name", "Price", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Entry");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search");

        jLabel3.setText("TotalPrice");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("0.0");

        jRadioButton1.setText("Cash");

        jRadioButton2.setText("Card");

        jRadioButton3.setText("UPI");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Phone number");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton3))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       int mp=0,c=0;
         try
            {mp=Integer.valueOf(jTextField1.getText());}
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Enter valid quantity","Failed ", JOptionPane.ERROR_MESSAGE);
             return;
                }
         PreparedStatement ps;
         String a;
         a="Select * from IC where BarCodeId=?";
        try {
            connect i=new connect();
            ps=(PreparedStatement) i.con.prepareStatement(a);
            ps.setInt(1, mp);
            ResultSet rs;
           rs = ps.executeQuery();
             Object[] r=new Object[4],r1=new Object[5];
            mo.setRowCount(0); 
        mo= (DefaultTableModel)jTable2.getModel();
        if(!rs.next())
        {
            JOptionPane.showMessageDialog(this, "Enter valid BarCode","Failed ", JOptionPane.ERROR_MESSAGE);
             return;
        }
         do
         {
             //String Us,String pa,String ro,String date,int a,int id
              // "UserId", "UserName", "Password", "Age", "Role", "DateJoining"
                     r1[3]=1;
                     r1[1]=rs.getString("Name");
             r1[2]=rs.getString("Price");
             r1[0]=rs.getString("UniqueId");
             r1[4]=(int)r1[3]*Float.valueOf((String) r1[2]);
            
              r[0]=mp;
               r[2]=rs.getString("Name");
             r[3]=rs.getString("Price");
             r[1]=rs.getString("UniqueId");
              mo.addRow(r);
             c++;
         }while(rs.next());
         
        
           if(c==1)
           {
                mo1= (DefaultTableModel)jTable1.getModel();
                mo1.addRow(r1);
           }
           else
           {
               jFrame1.setVisible(true);
               
               
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i=jTable2.getSelectedRow();
        if(i==-1){
                    JOptionPane.showMessageDialog(jFrame1, "Select a row to proceed","Failed ", JOptionPane.ERROR_MESSAGE);
                }
        else{
            Object [] r1=new Object[5];
            r1[3]=1;
                     r1[1]=jTable2.getValueAt(i, 2);
             r1[2]=jTable2.getValueAt(i, 3);
             r1[0]=jTable2.getValueAt(i, 1);
             r1[4]=Float.valueOf((String) r1[2])*(int)r1[3];
              mo1= (DefaultTableModel)jTable1.getModel();
             mo1.addRow(r1);
             jFrame1.setVisible(false);
                }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             long mp=0,c=0;
         try
            {mp=Long.valueOf(jTextField3.getText());}
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Enter valid number","Failed ", JOptionPane.ERROR_MESSAGE);
                    jTextField3.setText("");
             return;
                }
         if(jTextField3.getText().length()!=10)
         {
             JOptionPane.showMessageDialog(this, "Number length is not 10","Failed ", JOptionPane.ERROR_MESSAGE); return;
         }
        int i=-1;
            i=JOptionPane.showConfirmDialog(this, buttonGroup1.getSelection().getActionCommand()+ " is Selected. Are to sure to proceed ?","Warning ",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if(i!=0)return;
        PreparedStatement ps;
        ResultSet rs;
        String t="Select * from people where phonenumber="+jTextField3.getText();
        try {
            connect re=new connect();
            ps=(PreparedStatement) re.con.prepareStatement(t);
            rs=ps.executeQuery();
            if(!rs.next())
            {
                jFrame2.setVisible(true);
                return;
            }
            else
            {
                int u=rs.getInt("count"),j;
                t="Update people SET count= "+String.valueOf(++u)+" where ID = "+rs.getString("ID");
                ps=(PreparedStatement) re.con.prepareStatement(t);
                ps.executeUpdate();
                Date d;
                d = new Date();
             SimpleDateFormat ft = 
                            new SimpleDateFormat ("yyyy_MM_dd_hh_mm_ssa");
            File df = new File(address+rs.getString("phonenumber")+"\\"+ft.format(d)+".txt");
            df.createNewFile();
            FileWriter f = new FileWriter(address+rs.getString("phonenumber")+"\\"+ft.format(d)+".txt");
            f.write(String.format("%-10s %-15s %-10s %-10s %-10s","UniqueId","Name","price","quantity","Totalprice"));
             f.write("\n\n");
            for(i=0;i<jTable1.getRowCount();i++)
            {
                 t="UPDATE IC SET Quantity = Quantity-"+String.valueOf(jTable1.getValueAt(i, 3))+" WHERE UniqueId = "+ String.valueOf(jTable1.getValueAt(i, 0));
               
                ps.executeUpdate(t);
                f.write(String.format("%-10s %-15s %-10s %-10s %-10s",String.valueOf(jTable1.getValueAt(i, 0)),String.valueOf(jTable1.getValueAt(i, 1)),String.valueOf(jTable1.getValueAt(i, 2)),String.valueOf(jTable1.getValueAt(i, 3)),String.valueOf(jTable1.getValueAt(i, 4))));
                f.write("\n");
            }
              f.close();
              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                 JOptionPane.showMessageDialog(this, "Data stored successfully","Success ", JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        long mp=0,c=0;
         try
            {mp=Long.valueOf(jTextField3.getText());}
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Enter valid number","Failed ", JOptionPane.ERROR_MESSAGE);
                    jTextField3.setText("");
             return;
                }
         if(jTextField3.getText().length()!=10)
         {
             JOptionPane.showMessageDialog(this, "Number length is not 10","Failed ", JOptionPane.ERROR_MESSAGE); 
         }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        String h=jTextField4.getText();
        if(h=="")
        {
            JOptionPane.showMessageDialog(this, "Enter a name","Failed ", JOptionPane.ERROR_MESSAGE); 
            return;
        }
        else
        {
           
            
            int j,i;
               String t="Insert into people (phonenumber,Name,count) values (?,?,1)";
                Date d;
                d = new Date();
             SimpleDateFormat ft = new SimpleDateFormat ("yyyy/MM/dd_hh:mm:ssa");
              File file = new File(address+"\\"+jTextField3.getText());
            boolean bool = file.mkdirs();
            
            try {
                PreparedStatement ps;
                ps=(PreparedStatement) connect.con.prepareStatement(t);
                ps.setString(1, jTextField3.getText());
                ps.setString(2, jTextField4.getText());
                ps.executeUpdate();
                File df = new File(address+jTextField3.getText()+"\\"+ft.format(d)+".txt");
            df.createNewFile();
            FileWriter f;
                f = new FileWriter(address+jTextField3.getText()+"\\"+ft.format(d)+".txt");
                 f.write(String.format("%-10s %-15s %-10s %-10s %-10s","UniqueId","Name","price","quantity","Totalprice"));
             f.write("\n\n");
            
              
            for(i=0;i<jTable1.getRowCount();i++)
            {
              t="UPDATE IC SET Quantity = Quantity-"+String.valueOf(jTable1.getValueAt(i, 3))+" WHERE UniqueId = "+ String.valueOf(jTable1.getValueAt(i, 0));
               ps.executeUpdate(t);
                f.write(String.format("%-10s %-15s %-10s %-10s %-10s",String.valueOf(jTable1.getValueAt(i, 0)),String.valueOf(jTable1.getValueAt(i, 1)),String.valueOf(jTable1.getValueAt(i, 2)),String.valueOf(jTable1.getValueAt(i, 3)),String.valueOf(jTable1.getValueAt(i, 4))));
                f.write("\n");
            }
             f.close();
                
                jFrame2.setVisible(false);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                      JOptionPane.showMessageDialog(this, "Data stored successfully","Success ", JOptionPane.INFORMATION_MESSAGE);
                     
            } catch (IOException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField3FocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        PreparedStatement st;
           String t="Update log set logout=? where ID=?";
           connect i;
        java.util.Date d = new java.util.Date();
             SimpleDateFormat ft =  new SimpleDateFormat ("yyyy/MM/dd hh:mm:ss-a");
             String h=ft.format(d);
        try {
            i = new connect();
             st = (PreparedStatement) i.con.prepareStatement(t);
                 st.setString(1,h);
                 st.setInt(2,ID);
                 st.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_formWindowClosing
      
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cashier().setVisible(true);
        });
    }
    private String address="";
    public static int ID=0;
private DefaultTableModel mo=new DefaultTableModel();
private DefaultTableModel mo1=new DefaultTableModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
