/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtable;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RAMYAMUKESH
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 48, -1, -1));

        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 101, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 139, -1, -1));

        jTextField1.setText("Hello");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 98, 112, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 204, -1, -1));

        jPasswordField1.setText("Power");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 136, 112, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            // TODO add your handling code here:
            ResultSet rs;
        String un= jTextField1.getText();
        String ps= String.valueOf(jPasswordField1.getPassword());
        String g= "SELECT * FROM `control` WHERE `Username` = ? AND `Password` = ? ";
             PreparedStatement st;
             
            
        try {
             connect i= new connect();
            st = i.con.prepareStatement(g);
            st.setString(1, un);
             st.setString(2, ps);
             rs=st.executeQuery();
             if(rs.next())
             {
                 //ok accepted
                 
                 if("Admin".equals(rs.getString("Role")))
                 {
                    g= "insert into log (username,Role,login,logout) values (?,?,?,\"WorkingOn\")";
                    
            st = i.con.prepareStatement(g);
            st.setString(1, un);
             st.setString(2, rs.getString("Role"));
              java.util.Date d;
                d = new java.util.Date();
             SimpleDateFormat ft =  new SimpleDateFormat ("yyyy/MM/dd hh:mm:ss-a");
             String h=ft.format(d);
             st.setString(3,h);
             st.executeUpdate();
                 g="SELECT * from log where login=?";
                 st = i.con.prepareStatement(g);
                 st.setString(1,h);
                 rs=st.executeQuery();
                 rs.next();
                 AdminFrame.ID=rs.getInt("ID");
                   java.awt.EventQueue.invokeLater(() -> {
                         try {
                             new AdminFrame().setVisible(true);
                         } catch (SQLException ex) {
                             Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
                         }
           
                    });
                   
                 }
                 else if("Cashier".equals(rs.getString("Role")))
                 {
                             g= "insert into log (username,Role,login,logout) values (?,?,?,\"WorkingOn\")";
                    
            st = i.con.prepareStatement(g);
            st.setString(1, un);
             st.setString(2, rs.getString("Role"));
              java.util.Date d;
                d = new java.util.Date();
             SimpleDateFormat ft =  new SimpleDateFormat ("yyyy/MM/dd hh:mm:ss-a");
             String h=ft.format(d);
             st.setString(3,h);
             st.executeUpdate();
                 g="SELECT * from log where login=?";
                 st = i.con.prepareStatement(g);
                 st.setString(1,h);
                 rs=st.executeQuery();
                 rs.next();
                 Cashier.ID=rs.getInt("ID");
                   java.awt.EventQueue.invokeLater(() -> {
                       new Cashier().setVisible(true);        
                    });
                   
                 }
                 else if("InventoryControl".equals(rs.getString("Role")))
                 {
                             g= "insert into log (username,Role,login,logout) values (?,?,?,\"WorkingOn\")";
                    
            st = i.con.prepareStatement(g);
            st.setString(1, un);
             st.setString(2, rs.getString("Role"));
              java.util.Date d;
                d = new java.util.Date();
             SimpleDateFormat ft =  new SimpleDateFormat ("yyyy/MM/dd hh:mm:ss-a");
             String h=ft.format(d);
             st.setString(3,h);
             st.executeUpdate();
                 g="SELECT * from log where login=?";
                 st = i.con.prepareStatement(g);
                 st.setString(1,h);
                 rs=st.executeQuery();
                 rs.next();
                 InventoryControl.ID=rs.getInt("ID");
                   java.awt.EventQueue.invokeLater(() -> {
                         try {
                             new InventoryControl().setVisible(true);
                         } catch (SQLException ex) {
                             Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
                         }
           
                    });
                   
                 }
             
                 
                this.setVisible(false);
             }
             else
             {
                 //error
                 JOptionPane.showMessageDialog(null, "Invalid username/password", "Login error", 2);
             }
        } catch (SQLException ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        
        
        
    
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[])throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       Class.forName ("com.mysql.jdbc.Driver");
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
